//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EndlessUsbTool.rc
//
#define IDR_MAINFRAME					128
#define IDD_ENDLESSUSBTOOL_DIALOG				102
#define IDR_HTML_ENDLESSUSBTOOL_DIALOG			103
#define IDR_HTML_ENDLESSUSBTOOL_CSS				104
#define IDR_HTML_ENDLESSUSBTOOL_JS				105


#define IDR_IMG_PAGE_INDICATOR				200
#define IDR_IMG_PAGE_INDICATOR_SEL			201
#define IDR_IMG_LEFT_PANEL_IMAGE			202
#define IDR_IMG_RIGHT_PANEL_IMAGE			203
#define IDR_IMG_MAGNIFYING_GLASS			204
#define IDR_IMG_SECURE_BOOT					205

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		101
#define _APS_NEXT_COMMAND_VALUE		32771
#endif
#endif
